### PR TITLE
standardize the http package

### PR DESCRIPTION
**Pull request by piusalfred**
Refactoring the http package to enable both `encoding` and `decoding` on a package level.
Make every request use the Send for making HTTP calls.

### CODE REVIEW

**Comment by piusalfred** [comment]
take a look here to these [changes](https://github.com/piusalfred/whatsapp/pull/22/commits/fe6ac6994244e927712eea3fae04edd4f10fecf5)

@bcmmbaga

**Comment by piusalfred** [comment]
This is how Send looks like now

https://github.com/piusalfred/whatsapp/blob/fe6ac6994244e927712eea3fae04edd4f10fecf5/messages.go#L60-L99

**Comment by piusalfred** [comment]
Send is looking like this

https://github.com/piusalfred/whatsapp/blob/fe6ac6994244e927712eea3fae04edd4f10fecf5/http/http.go#L229-L286

**Review by bcmmbaga — COMMENTED** [review]
minor change otherwise looks good to me

**Review by bcmmbaga — APPROVED** [review]

**Pull request merged**
